
CREATE TABLE IF NOT EXISTS WAY
(
    OSM_ID              INTEGER PRIMARY KEY NOT NULL,
    WAY_NAME            TEXT,
    HIGHWAY             TEXT,
    MAXSPEED_MPH        INTEGER,
    MAXSPEED_RULE       TEXT,
    LANE_COUNT          INTEGER,
    LANE_COUNT_RULE     TEXT,
    ONE_WAY             BOOLEAN,
    CONDITION           TEXT
);

CREATE TABLE IF NOT EXISTS CYCLEWAY
(
    WAY_OSM_ID          INTEGER PRIMARY KEY NOT NULL REFERENCES WAY(OSM_ID),
    CYCLEWAY_TYPE       TEXT,
    CYCLEWAY_LANE       TEXT,
    CYCLEWAY_SURFACE    TEXT,
    LEFT_TYPE           TEXT,
    LEFT_LANE           TEXT,
    LEFT_WIDTH          TEXT,
    LEFT_BUFFER         BOOLEAN,
    LEFT_SEPARATION     TEXT,
    LEFT_REVERSED       BOOLEAN,
    RIGHT_TYPE          TEXT,
    RIGHT_LANE          TEXT,
    RIGHT_WIDTH         TEXT,
    RIGHT_BUFFER        BOOLEAN,
    RIGHT_SEPARATION    TEXT,
    RIGHT_REVERSED      BOOLEAN
);



CREATE TABLE IF NOT EXISTS LEVEL_OF_TRAFFIC_STRESS
(
    WAY_OSM_ID                  INTEGER PRIMARY KEY NOT NULL REFERENCES WAY(OSM_ID),
    LTS                         INTEGER,
    LTS_FWD                     INTEGER,
    LTS_REV                     INTEGER,
    BIKE_ACCESS                 INTEGER,
    BIKE_ACCESS_FWD             INTEGER,
    BIKE_ACCESS_REV             INTEGER,
    SEPARATION_FWD              INTEGER,
    SEPARATION_REV              INTEGER,
    MIXED_FWD                   INTEGER,
    MIXED_REV                   INTEGER,
    BIKE_LANE_NO_PARKING_FWD    INTEGER,
    BIKE_LANE_NO_PARKING_REV    INTEGER,
    BIKE_LANE_YES_PARKING_FWD   INTEGER,
    BIKE_LANE_YES_PARKING_REV   INTEGER
);

CREATE TABLE IF NOT EXISTS NODE
(
    OSM_ID              INTEGER PRIMARY KEY NOT NULL,
    LATITUDE            REAL NOT NULL,
    LONGITUDE           REAL NOT NULL,
    HIGHWAY             TEXT,
    TRAFFIC_CALMING     TEXT,
    CROSSING            TEXT,
    CROSSING_MARKINGS   TEXT,
    CROSSING_ISLAND     TEXT
);

CREATE TABLE IF NOT EXISTS NODE_WAY
(
    WAY_OSM_ID      INTEGER NOT NULL REFERENCES WAY(OSM_ID),
    NODE_OSM_ID     INTEGER NOT NULL REFERENCES NODE(OSM_ID),
    POSITION        INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS NODE_WAY_IDX ON NODE_WAY(WAY_OSM_ID, NODE_OSM_ID)