# Speeds
s1:
  english: 20
  metric: 35
s2:
  english: 25
  metric: 40
s3:
  english: 30
  metric: 50
s4:
  english: 35
  metric: 55
s5:
  english: 40
  metric: 65
s6:
  english: 50
  metric: 80
s7:
  english: 65
  metric: 100

# Widths
w1:
  english: 5.5
  metric: 1.7
w2:
  english: 13.45
  metric: 4.1
w3:
  english: 13.95
  metric: 4.25
w4:
  english: 14.75
  metric: 4.5
